services:
  - type: web
    name: smart-warehouse-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
